FROM openjdk:17-jdk-slim-buster

ENV JAVA_HOME /opt/java/openjdk
ENV SPRING_DATASOURCE_URL=jdbc:h2:mem:CinemaDB;DB_CLOSE_DELAY=-1
ENV SPRING_DATASOURCE_USERNAME=sa
ENV SPRING_DATASOURCE_PASSWORD=
ENV SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
ENV SPRING_H2_CONSOLE_ENABLED=true
ENV SPRING_H2_CONSOLE_PATH=/h2
ENV SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=update
ENV SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.H2Dialect
ENV SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=true
ENV SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
ENV APPLICATION_SECURITY_JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
ENV APPLICATION_SECURITY_JWT_EXPIRATION=86400000
ENV APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION=604800000
ENV SPRINGDOC_ENABLE_SPRING_SECURITY=true
ENV SPRING_JPA_OPEN_IN_VIEW=true

WORKDIR /app

COPY target/Cinema-0.0.1-SNAPSHOT.jar /app/cinema-app.jar

RUN apt-get update && apt-get install -y libh2-java

EXPOSE 8080

CMD ["java", "-jar", "cinema-app.jar"]